# pyre-ignore-all-errors
"""
Pre-Delinquency Intervention Engine - Model Integrity Checker

Verifies ML model files against SHA-256 checksums before loading to
prevent tampered or corrupted artefacts from entering the scoring pipeline.
"""
import hashlib
import json
import logging
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)

SUPPORTED_EXTENSIONS = {".pkl", ".joblib", ".pt"}


def compute_checksum(path: str | Path, *, chunk_size: int = 1 << 16) -> str:
    """Return the SHA-256 hex digest of a file."""
    sha256 = hashlib.sha256()
    with open(path, "rb") as f:
        while chunk := f.read(chunk_size):
            sha256.update(chunk)
    return sha256.hexdigest()


def verify_model(model_path: str | Path, checksums_path: str | Path) -> None:
    """Verify a model file against checksums.json.

    Raises:
        FileNotFoundError: If the model or checksums file does not exist.
        RuntimeError: If the checksum does not match.
    """
    model_path = Path(model_path)
    checksums_path = Path(checksums_path)

    with open(checksums_path) as f:
        checksums: dict = json.load(f)

    filename = model_path.name
    expected = checksums.get(filename)
    if expected is None:
        raise RuntimeError(
            f"No checksum entry for '{filename}' in {checksums_path}. "
            f"Regenerate checksums after training."
        )

    actual = compute_checksum(model_path)
    if actual != expected:
        raise RuntimeError(
            f"Checksum mismatch for '{filename}':\n"
            f"  expected: {expected}\n"
            f"  actual:   {actual}\n"
            f"Model file may be corrupted or tampered with."
        )

    logger.info("Checksum OK for %s", filename)


def load_verified_model(
    model_path: str | Path,
    checksums_path: str | Path,
    loader_func: Callable[[str | Path], Any],
) -> Any:
    """Verify integrity then load the model using the provided loader function."""
    verify_model(model_path, checksums_path)
    return loader_func(model_path)


def generate_checksums(model_dir: str | Path, output_path: str | Path) -> dict[str, str]:
    """Generate checksums.json for all model files in a directory.

    Scans for files with extensions: .pkl, .joblib, .pt
    """
    from datetime import datetime, timezone

    model_dir = Path(model_dir)
    output_path = Path(output_path)

    checksums: dict[str, str] = {
        "_note": "Auto-generated by ml/model_loader.py during training. Do not edit manually.",
        "_generated_at": datetime.now(timezone.utc).isoformat(),
    }

    for ext in sorted(SUPPORTED_EXTENSIONS):
        for filepath in sorted(model_dir.glob(f"*{ext}")):
            checksums[filepath.name] = compute_checksum(filepath)
            logger.info("Checksummed %s", filepath.name)

    with open(output_path, "w") as f:
        json.dump(checksums, f, indent=2)

    logger.info("Wrote checksums to %s (%d models)", output_path, len(checksums) - 2)
    return checksums
