apiVersion: 1

datasources:
  - name: PostgreSQL-PDI
    type: postgres
    access: proxy
    url: pdi-postgres:5432
    database: pdi_db
    user: pdi_user
    secureJsonData:
      password: pdi_password
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
